name: deepdive
channels:
- conda-forge
dependencies:
  - python==3.9.18
  - pip
  - pip:
    - torch==2.1.2
    - pytorch-lightning=2.1.1
    - torchvision=0.16.2
    - torchmetrics==1.2.0
    - matplotlib
    - seaborn
    - importlib
    - requests
    
