name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install repo2docker
        run: pip install jupyter-repo2docker

      - name: Build Docker Image
        run: jupyter-repo2docker --no-run .

      - name: Push Docker Image to Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .binder/Dockerfile
          push: true
          tags: |
            docker.io/lrettenberger/DeepDive:latest
